"""Train the delay-risk model on Jan-2019 BTS data.

Outputs (gitignored, regenerated by this script):
  data/model.pkl         - sklearn LogisticRegression pipeline (P(ARR_DEL15))
  data/cancel_rates.json - per-carrier cancellation base rate + global default

Run:  python data/train_model.py
"""
from pathlib import Path
import json
import joblib
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

DATA = Path(__file__).parent
TRAIN_CSV = DATA / "Jan_2019_ontime.csv"

# Features match the Prior agent's predict_prior(...) args exactly.
FEATURES = ["OP_UNIQUE_CARRIER", "ORIGIN", "DEST", "DAY_OF_WEEK", "DEP_TIME_BLK"]
TARGET = "ARR_DEL15"


def load(csv: Path) -> pd.DataFrame:
    cols = FEATURES + [TARGET, "CANCELLED"]
    df = pd.read_csv(csv, usecols=cols)
    # DAY_OF_WEEK is treated as a category (1..7), not a number
    df["DAY_OF_WEEK"] = df["DAY_OF_WEEK"].astype("Int64").astype(str)
    return df


def main() -> None:
    df = load(TRAIN_CSV)

    # --- Delay model: cancelled/diverted rows have no ARR_DEL15, drop them ---
    d = df.dropna(subset=[TARGET])
    X, y = d[FEATURES], d[TARGET].astype(int)
    pre = ColumnTransformer(
        [("oh", OneHotEncoder(handle_unknown="ignore"), FEATURES)]
    )
    model = Pipeline([("pre", pre), ("clf", LogisticRegression(max_iter=1000))])
    model.fit(X, y)
    joblib.dump(model, DATA / "model.pkl")

    # --- Cancellation base rate per carrier (carrier-level is stable) ---
    cancel = df.groupby("OP_UNIQUE_CARRIER")["CANCELLED"].mean().round(4).to_dict()
    out = {"by_carrier": cancel, "global": round(float(df["CANCELLED"].mean()), 4)}
    (DATA / "cancel_rates.json").write_text(json.dumps(out, indent=2))

    print(f"trained on {len(d):,} flights | delay base rate {y.mean():.3f}")
    print(f"global cancel rate {out['global']:.3f} | carriers {len(cancel)}")
    print("saved: data/model.pkl, data/cancel_rates.json")


if __name__ == "__main__":
    main()
